
replicaCount: 1

image:
  repository: mianmahroz/gateway-service
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  name: gateway
  targetport: 8080

container:
  name: gateway-service


#cpa:
#  podAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchExpressions:
#            - key: app
#              operator: In
#              values:
#                - react-ui
#        topologyKey: "kubernetes.io/hostname"