#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: delivery
#          uri: lb://DELIVERY
#          predicates:
#            - Path=/delivery/**
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order/**
#

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - OPTIONS
              - POST
            allowCredentials: true
management:
  endpoint:
    gateway:
      enabled: true
