management.endpoint.health.show-details: always

spring:
  kafka:
    listener:
      missingTopicsFatal: false
    consumer:
      properties.spring.json.trusted.packages: com.mahroz.testcontainers.dto,
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  sql:
    init:
      mode: never

logging:
  level:
    org:
      springframework:
        boot:
          devtools:
            restart: DEBUG

management:
  info:
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true


