apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: using-kubernates
build:
  artifacts:
    - image: mianmahroz/order-service
      context: order-service
      docker:
        dockerfile: Dockerfile
    - image: mianmahroz/delivery-service
      context: delivery-service
      docker:
        dockerfile: Dockerfile
    - image: mianmahroz/identity-service
      context: identity-service
      docker:
        dockerfile: Dockerfile
    - image: mianmahroz/gateway-service
      context: gateway-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: order-helm
        chartPath: ./order-service/order-helm
      - name: delivery-helm
        chartPath: ./delivery-service/delivery-helm
      - name: identity-helm
        chartPath: ./identity-service/identity-helm
      - name: gateway-helm
        chartPath: ./gateway-service/gateway-helm



