apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  labels:
    {{- include "order-helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      name: http
  selector:
    {{- include "order-helm.selectorLabels" . | nindent 4 }}
