
replicaCount: 1

image:
  repository: mianmahroz/identity-service
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8084
  name: identity
  targetport: 8084

container:
  name: identity-service


#cpa:
#  podAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchExpressions:
#            - key: app
#              operator: In
#              values:
#                - react-ui
#        topologyKey: "kubernetes.io/hostname"